### ISSUE TITLE
README is broken on mobile

### ISSUE THREAD

**Issue by ZackeryRSmith** [anic17/Newtrodit#11]
I was just viewing the repo on my phone and it seems that the readme is all messed up and quite hard to read. I know this really has no bearing on much, as most of the views are on a desktop. I’m not even sure if it’s a fixable thing but I’ll look into it

**Comment by anic17** [comment]
The only "issue" with the readme from the mobile application is the contributors table. Furthermore, the readme rendering is not something I have control about. Would you mind sending a screenshot about what you see?

**Comment by ZackeryRSmith** [comment]
The README isn't really "broken" other then, as you mentioned, the contributor table. As you have no control over this issue I am marking it as closed.
