### ISSUE TITLE
Issue with clicking

### ISSUE THREAD

**Issue by ZackeryRSmith** [anic17/Newtrodit#12]
When clicking around in Newtrodit the first click works fine, but it changes the window title to what seems like debug text, and I can no longer click around. Pressing ESC allows you to click again. Is this intended?

**Comment by anic17** [comment]
This is a debug message I forgot to remove when trying to fix that exact same issue you're facing. Hope I'll get some time to fix it, I'll let you know when I do.

**Comment by backkslashh** [comment]
Why haven't this been closed yet?
