### ISSUE TITLE
Unexpected crash

### ISSUE THREAD

**Issue by ZackeryRSmith** [anic17/Newtrodit#13]
When pressing CTRL+X with text on the same line the program will then crash in a few moments. I would assume the expected behavior of doing this is to cut the whole line as many other editors do.

https://github.com/anic17/Newtrodit/assets/72983221/85346ba4-4e26-4774-ae04-74db43be6132

**Comment by anic17** [comment]
I was able to reproduce the exact same issue and it's fixed on the latest version. I will commit it as soon as possible and then I will close the issue. 
Thank you for your contribution, they are greatly appreciated!
