### ISSUE TITLE
Feature Idea

### ISSUE THREAD

**Issue by ZackeryRSmith** [anic17/Newtrodit#2]
Adding a color column like vim does would be nice if not already implemented. I'm not too sure where you want to bring Newtrodit but I think it would be nice to have some form of a config

**Comment by anic17** [comment]
I'm not familiar with vim. There's already a way to configure Newtrodit, by creating a file called `newtrodit.config`, which allows you to change color schemes. There's also syntax highlighting and you can make your own highlighting rules to customize even more Newtrodit.
