### ISSUE TITLE
Segfault after --help

### ISSUE THREAD

**Issue by mrHeavenli** [anic17/Newtrodit#3]
Here's the debug info:
Debug info:

errno: 0x2 (No such file or directory)
GetLastError: 0x0
Reason: Segmentation fault. Signum code: 11

My specs: 
OS Name	Microsoft Windows 10 Home
Processor	11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz   1.69 GHz
System Type	x64-based PC
System Model	Inspiron 7400

Compiled using:
gcc (i686-win32-dwarf-rev0, Built by MinGW-W64 project) 8.1.0
command: "gcc Newtrodit.c -o Newtrodit.exe -luser32 -O2"

This error can be recreated by running "Newtrodit.exe --help"
and then pressing the up/down key twice.

**Comment by anic17** [comment]
I can't seem to reproduce the issue, even with the same compilation command-line and the exact same action. Regardless, thank you for contributing to Newtrodit.
