### ISSUE TITLE
F1 - Help menu, needs Left-right key assigned properly!

### ISSUE THREAD

**Issue by TheKvc** [anic17/Newtrodit#7]
In the "F1" help menu...

Up-down is working fine, but when I press - Left/Right.. it just jumps to the next page on {Right}, but does the same on pressing {Left} arrow key too, I expected it to go back to the previous page, as up and down has similar (not same, but similar) functionality.

https://github.com/anic17/Newtrodit/assets/46124093/7ea6334c-51da-4260-905e-2277ac51cf1b

**Comment by anic17** [comment]
Thank you for bringing this into attention.
I am going to implement this.
What do you think the behavior should be?
Going a page back or just a line?

**Comment by ZackeryRSmith** [comment]
> ... pressing {Left} arrow key too, I expected it to go back to the previous page ...
by reading this I assume that he means left arrow should be page up while right is page down.

going back just a line or forward a line like the up and down arrow keys doesn't really do much. To me it's a waste of binds, and someone nonsensical for the left and right arrows keys to have the same function as the up and down arrows. That's just my opinion on it though :P

**Comment by anic17** [comment]
> > ... pressing {Left} arrow key too, I expected it to go back to the previous page ...
> by reading this I assume that he means left arrow should be page up while right is page down.
> 
> going back just a line or forward a line like the up and down arrow keys doesn't really do much. To me it's a waste of binds, and someone nonsensical for the left and right arrows keys to have the same function as the up and down arrows. That's just my opinion on it though :P

What would the expected behavior be for you?

**Comment by ZackeryRSmith** [comment]
For me it would behave how `man` works. It allows you to scroll to the left or right of the document, so if text goes off screen you can read it. But obviously you don't need that in this case, so I think implementing them as page key equivalents like TheKvc has suggested would be nice,

**Comment by anic17** [comment]
> For me it would behave how `man` works. It allows you to scroll to the left or right of the document, so if text goes off screen you can read it. But obviously you don't need that in this case, so I think implementing them as page key equivalents like TheKvc has suggested would be nice,

Alright, I'm going to bind them to page up/page down. Thank you both of you.

**Comment by anic17** [comment]
This feature has been implemented now. Appreciate your feedback.

I am closing this issue now.

**Comment by TheKvc** [comment]
Awesome, This is actually what I was suggesting exactly. Thankyou for implementing and taking suggestions from both of you. This is an awesome project.
